# Generated by Django 5.1.6 on 2025-03-02 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Напишите название', max_length=250, verbose_name='Название поста')),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField(help_text='Напишите описание', verbose_name='Содержание поста')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания поста')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления поста')),
                ('status', models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликован')], default='DF', max_length=2, verbose_name='Статус состояния поста (Черновик/Опубликован)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='blog_post_publish_bb7600_idx')],
            },
        ),
    ]
